name: Deploy Website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: docker://ghcr.io/scottbrenner/cfn-lint-action:master
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-southeast-2
      - name: Lint
        uses: ScottBrenner/cfn-lint-action@v2
      - name: Deploy
        run: bash deploy.sh
