name: Deploy Website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::156041440685:role/adowen-website-GitHubActionsRole-mBO6jcwZvOPB
          aws-region: ap-southeast-2
      - name: Deploy
        run: bash deploy.sh
