name: Deploy Website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-southeast-2
      - name: Lint
        # We use the docker image instead of the marketplace version because the
        # docker image is way faster because it doesn't have to download
        # cfn-lint every time
        uses: docker://ghcr.io/scottbrenner/cfn-lint-action:master
      - name: Deploy
        run: bash deploy.sh
